# Generated by Django 3.0.3 on 2020-02-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drunk', '0003_auto_20200219_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='cocktail_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='cocktail_recipe',
            new_name='recipe',
        ),
    ]
