# Generated by Django 3.0.3 on 2020-02-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drunk', '0005_auto_20200219_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='picture',
            field=models.ImageField(upload_to='cocktail_images/'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='recipe',
            field=models.TextField(max_length=256),
        ),
    ]
