# Generated by Django 3.0.3 on 2020-03-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drunk', '0006_auto_20200221_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drunk.CocktailGroup'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cocktailreview',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drunk.Cocktail'),
        ),
        migrations.AlterField(
            model_name='cocktailreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
